//
//  OPContactModel.h
//  OPay
//
//  Created by LiuHuan on 2019/4/23.
//  Copyright © 2019 Opera. All rights reserved.
//

#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

@interface OPContactModel : NSObject

/**
 *  Generated by CNContactFormatter
 *  style: CNContactFormatterStyleFullName
 */
@property (copy, nonatomic) NSString *fullName;
@property (copy, nonatomic) NSString *phoneNumber;

@end

NS_ASSUME_NONNULL_END
